config/routes.rb
Omniauthpls::Application.routes.draw do
 
  resources :users
  resources :groups, only: ['index', 'show'] 

  # get 'https://betterreads.herokuapp.com/auth/goodreads/callback', :to => 'sessions#create'
  get '/auth/:goodreads/callback', :to => 'sessions#create'
  root :to => "users#create"
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'group/send_alert/:group_id', to: 'groups#send_alert', as: 'group_send_alert'
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_and_belongs_to_many :members

  before_create :set_status

  def set_status 
  	self.status = "created"	
  end
end

app/controllers/group_controller.rb
class GroupController < ApplicationController
  require 'rubygems'
  require 'nokogiri'
  require 'open-uri'

  def index
    client = Goodreads::Client.new(oauth_token: "ALIVGfWdLZYkh34NIKzVmw", api_key: 'UpIly3BURwhZ52tmj4ag', api_secret: GOODREADS_API_SECRET)
    @group_list = client.group_list(current_user.uid, 'sort')
    @group_list.group.each do |g| 
  
    @group_id = g.id 
  end
  end


  def show
   client = Goodreads::Client.new(oauth_token: "ALIVGfWdLZYkh34NIKzVmw", api_key: 'UpIly3BURwhZ52tmj4ag', api_secret: GOODREADS_API_SECRET)
    @reviews = client.book_by_title("Moby Dick")
    @group_list = client.group_list(current_user.uid, 'sort')
    # @group = client.group(106427)
    # @members = @group.group_members
    if @group_list.group[0].nil?
       url = "https://www.goodreads.com/group/#{@group_list.group.id}/members?format=xml&key=#{client.api_key}"
    else
      url = "https://www.goodreads.com/group/#(params[:id])/members?format=xml&key=#{client.api_key}"
    end
# @group_list.group[1].id
    doc = Nokogiri::HTML(open(url))
    group = doc.xpath("//id").map{ |tr| tr.xpath("//id").map(&:text) }[0]
    @group = group.map do |id| 
      begin
        url = "https://www.goodreads.com/user/show/#{id}.xml?key=#{client.api_key}"
        dic = Nokogiri::HTML(open(url))
        dic.xpath("//location").text.titleize 
        # dic.xpath("//name")[0].text
      rescue
      end
    end
    @name = []
    @city = []
    group.map do |id|
      begin
        url = "https://www.goodreads.com/user/show/#{id}.xml?key=01QcdA8pt51gOUi4UJj6A"
        dic = Nokogiri::HTML(open(url))
        x = dic.xpath("//name")[0].text || "no name"
        @name << x
        y = Geocoder.coordinates dic.xpath("//location").text
        if y.nil? 
          y = [0, 0]
        end
        @city << y
      rescue
      end
    end

    @location = @group.each_with_object(Hash.new(0)) { |word,counts| counts[word] += 1 }

  end

 end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # require 'rubygems'  require 'nokogiri'
  # require 'open-uri'

  def index
    @groups = current_user.groups 
  #   client = Goodreads::Client.new(oauth_token: @user.oauth_token, api_key: 'UpIly3BURwhZ52tmj4ag', api_secret: GOODREADS_API_SECRET)
  #   @group_list = client.group_list(@user.id, 'sort')
  
  #   @groups = @user.groups
    respond_to do |format|
      format.html 
      format.json do 
        render json: {
          groups_status: groups_status,
          group_total: current_user.group_total, 
          groups: current_user.groups.map do |g|
            { title: g.title,
              url: group_url(g),
              status: g.status, 
              total_members: g.num_members,
              populated_members: g.members.count }
          end
        }
      end
    end
  end


  def show
    @group = Group.find(params[:id])

    # TODO: move to helper
    @member_data = member_map_data(
      @group.members.includes(:location)
    )

    #client = Goodreads::Client.new(oauth_token: current_user.oauth_token, api_key: 'UpIly3BURwhZ52tmj4ag', api_secret: GOODREADS_API_SECRET)
    #@group_list = client.group_list(current_user.id, 'sort')
    #@group = Group.find_by_id(params[:id])
    #redirect_to(listgroups_path, :notice => 'Still Getting Data From Goodreads') unless @group

    # answer = []
    # @group_list.group.each { |g| answer.push(g.to_a.flatten) unless g.title != @group.title }
    # answer = answer.flatten
    # @percent_loaded = (((@group.users.count/answer[5].to_f)*100).to_i).to_s + '%'
  end

  private 
    def groups_status
      if current_user.group_total == current_user.groups.where(status: "populated").count
        "done"
      else
        "fetching"
      end
    end

   # input: array of members
   # output: array of hashes
   # [
   # { name: 'Steve Klebanoff", message_url: 'http://goodreads.com/message/new/5', lat: '53.434343', lng: '4343.4343', city: 'San Diego, CA' },
   # { ... },
   # { ... },
   # ]
    def member_map_data(members)
      all_locations = [] # NOTE: could use a hash, would be faster

      # TODO: optimize using pluck
      members.select {|m| m.location && m.location.city.present?}.map do |m|

        lat, lng = m.location.latitude, m.location.longitude
        if all_locations.include?(m.location.city)
          # randomize location
          lat, lng = Location.randomize_coords(lat, lng)
        end
        member_data = {name: m.name, message_url: "http://goodreads.com/message/new/#{m.goodreads_id}", 
          city: m.location.city, lat: lat, lng: lng}
        all_locations << m.location.city
        member_data
      end
    end
end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/index.html.erb
<div id="user-nav">
  <% if current_user %>
    Signed in as <%= current_user.name %>
    <%= link_to "Sign out", signout_path %>
  <% else %>
    <%= link_to "Sign in with Goodreads", "/auth/Goodreads" %>
  <% end %>
</div>

<body class = "index"> 
    <div class="groupsContainer">
      <p>Loading</p>
    </div>
</body> 

<script type='text/template' id='groupTemplate'>
  {{ if (status == 'populated') { }}
    <a href='{{= url }}'>{{= name }}</a>
  {{ } else { }}
    {{= name }}
  {{ } }}
  <br/>
  Group status: {{= status }}<br/>
  {{= populated_members }} / {{= total_members }}
  <div style='width: 300px; border: 1px solid black;'>
    <div style='width: {{= percent_populated }}%; background-color: green;'>
      &nbsp;
    </div>
  </div>
  <br/>
</script>

<script type="text/javascript">
   BetterReads.Groups.Index.setup();
</script>

app/views/groups/old_stuff.html.erb
<% if current_user.group_total.nil? %>
  <p>We are working on it</p>
<% elsif current_user.group_total == 0 %>
  <p>sorry, no groups</p>
<% else %>
  <div class = "grouplist"><h1><%= current_user.name %>'s Groups </h1></div>
  <div class = "groupl">
    <% if @groups.any? %>
      <% @groups.each do |g| %>
        <h2><%= link_to g.title, group_path(g.id), 'data-no-turbolink' => true %></h2>
        <span><%= g.status %></span>
      <% end %>
    <% else %>  
      <div class="popup"></div>
      <div class="wrapper1"></div>

      <h2>To see what the app can do, you must belong to some groups </h2><br>
        <%= button_to 'Join some reading groups', "https://www.goodreads.com/group", class: "push_button blue" , :method => :get , form: {target: '_blank'} %>
    <% end %>
  </div>
<% end %>

app/views/groups/show.html.erb
<div id="user-nav">
  <% if current_user %>
    Signed in as <%= current_user.name %>
    <%= link_to "Sign out", signout_path %>
  <% else %>
    <%= link_to "Sign in with Goodreads", "/auth/Goodreads" %>
  <% end %>
</div>
<div class = "back"> <%= link_to "Back to Groups Index", groups_path %> </div>
<body class = "index"> </body> 

<!-- google maps link: https://github.com/apneadiving/Google-Maps-for-Rails -->
<script type="text/javascript">
    function initialize() {
      handler = Gmaps.build('Google');
      handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
        markers = handler.addMarkers([
            
          <% @member_data.each do |m| %>
            <% if m[:lat] && m[:lng] %>
              {
                "lat": <%= m[:lat] %>,
                "lng": <%= m[:lng] %>,
                "infowindow": "<p class=members><%= m[:name] %> </p><p><%= m[:city] %></p>   <a href='<%= m[:message_url] %>' target='blank'>Message User</a>"
              },
            <% end %>
          <% end %>

        ]);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        handler.getMap().setZoom(2);
        handler.map.centerOn([25.0000, 13.0000]);

      });
    }

    google.maps.event.addDomListener(window, "load", initialize);
  </script>
<div style='width: 1000px;'>
  <div id="map" style='width: 1030px; height: 500px;'></div>
</div>

app/views/groups/untitled.html.erb
          <% @members.each do |member| %>
            <% if member.location %>
             <% y = "http://www.goodreads.com/message/new/#{member.goodreads_id}" %>
            {
              "lat": "<%= member.location.latitude %>",
              "lng": "<%= member.location.longitude %>",
              "infowindow": "<p class = members><%= member.name %> </p><p><%= member.location.city %></p>   <a href='<%= y %>', target='blank'>Message User</a> "
            },
            <% end %>
          <% end %>